require 'rubygems'
$:.unshift 'lib'
require 'caricature'


def csc
  system "gmcs"
  $?.pid.zero? ? "csc" : "gmcs"
end
 
desc "The default task is to run all the specs"
task :default => [:clr_models, :spec]

desc "Runs all the specs"
task :spec do
  puts "loading specs"
  system "ispec #{Dir.glob("spec/integration/*_spec.rb").join(' ')}"
end

desc "Compiles the clr models"
task :clr_models do
  Dir.chdir(File.dirname(__FILE__))
  files = Dir.glob("spec/fixtures/*.cs").join(' ') 
  system "#{csc} /noconfig /target:library /debug+ /debug:full /out:spec/bin/ClrModels.dll #{files}"
end

           

